POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "tranvudpqn123@gmail.com",
    "fullname": "Trần Vũ",
    "password": "Admin123@"
}

###
POST http://localhost:5000/api/auth/verify
Content-Type: application/json

{
    "email": "tranleanhvudpqn123@gmail.com"
}

###
POST http://localhost:5000/api/auth/check-username
Content-Type: application/json

{
    "username": "tranvudpqn123@gmail.com"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "tranleanhvudpqn123@gmail.com",
    "password": "Admin123@"
}

###
POST http://localhost:5000/api/auth/check-logged
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MDcxY2UyN2QwNTUyNjM0NjRkZGQ0OTQiLCJpYXQiOjE2MTgyOTYzNDN9.nPUynIn8YHmC5peBxJq0rYc88B3S-tJB6Fgi41lhLPg"
}


###
POST http://localhost:5000/api/store/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MDcxY2UyN2QwNTUyNjM0NjRkZGQ0OTQiLCJpYXQiOjE2MTgyOTYzNDN9.nPUynIn8YHmC5peBxJq0rYc88B3S-tJB6Fgi41lhLPg

{
    "brand": "Barista Shop",
    "alias": "barista-shop",
    "coverImage": "https://image.shutterstock.com/image-photo/cup-aromatic-coffee-beans-on-260nw-1249115137.jpg",
    "description": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    "descriptionImage": [],
    "logo": "https://png.pngtree.com/png-clipart/20190516/original/pngtree-coffee-logo-vintage-vector-icon-cafe-shop-element-illustration-emblem-isolated-png-image_3747240.jpg",
    "avatar": "https://www.mantruckandbus.com/fileadmin/media/bilder/02_19/219_05_busbusiness_interviewHeader_1485x1254.jpg"
}

###
PUT http://localhost:5000/api/store/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MDcxY2UyN2QwNTUyNjM0NjRkZGQ0OTQiLCJpYXQiOjE2MTgyOTYzNDN9.nPUynIn8YHmC5peBxJq0rYc88B3S-tJB6Fgi41lhLPg

{
    "brand": "Barista Shop Update",
    "alias": "barista-shop-update",
    "coverImage": "https://image.shutterstock.com/image-photo/cup-aromatic-coffee-beans-on-260nw-1249115137.jpg",
    "description": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    "descriptionImage": [],
    "logo": "https://png.pngtree.com/png-clipart/20190516/original/pngtree-coffee-logo-vintage-vector-icon-cafe-shop-element-illustration-emblem-isolated-png-image_3747240.jpg",
    "avatar": "https://www.mantruckandbus.com/fileadmin/media/bilder/02_19/219_05_busbusiness_interviewHeader_1485x1254.jpg"
}

# GEt info of store
###
GET http://localhost:5000/api/store/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MDcxY2UyN2QwNTUyNjM0NjRkZGQ0OTQiLCJpYXQiOjE2MTgyOTYzNDN9.nPUynIn8YHmC5peBxJq0rYc88B3S-tJB6Fgi41lhLPg


# ===========================================================================
# PRODUCT CATEGORY

# Add new product category
###
POST  http://localhost:5000/api/product-category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MDcxY2UyN2QwNTUyNjM0NjRkZGQ0OTQiLCJpYXQiOjE2MTgyOTYzNDN9.nPUynIn8YHmC5peBxJq0rYc88B3S-tJB6Fgi41lhLPg
Content-Type: application/json

{
    "title": "Paper Bag",
    "alias": "paper-bag"
}

# Get all product category
###
GET  http://localhost:5000/api/product-category


# ===========================================================================
# PRODUCT

# Add new product
###
POST  http://localhost:5000/api/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MDcxY2UyN2QwNTUyNjM0NjRkZGQ0OTQiLCJpYXQiOjE2MTgyOTYzNDN9.nPUynIn8YHmC5peBxJq0rYc88B3S-tJB6Fgi41lhLPg
Content-Type: application/json

{
    "avatar": "https://barista.qodeinteractive.com/wp-content/uploads/2016/03/product-image-12-633x633.jpg",
    "moreImage": [
        "https://barista.qodeinteractive.com/wp-content/uploads/2016/03/product-image-12-gallery-1-1-500x500.jpg",
        "https://barista.qodeinteractive.com/wp-content/uploads/2016/03/product-image-12-gallery-2-1-500x500.jpg",
        "https://barista.qodeinteractive.com/wp-content/uploads/2016/03/product-image-12-gallery-3-2-500x500.jpg",
        "https://barista.qodeinteractive.com/wp-content/uploads/2016/03/product-image-12-gallery-4-2-500x500.jpg",
        "https://barista.qodeinteractive.com/wp-content/uploads/2016/03/product-image-12-gallery-1-1-500x500.jpg"
    ],
    "title": "Recycled Bags",
    "alias": "recycled-bags",
    "productCategoryId": "607845f8f2dd005c5cbe1fc2",
    "price": "18,000",
    "shortDescription": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.",
    "detail": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    "sku": "01",
    "keySearch": [],
    "height": "0.3",
    "width": "0.3",
    "length": "0.3",
    "weight": "1",
    "listSale": [
        {
            "from": "5",
            "to": "10",
            "price": 5
        }
    ]
}